version: '3.7'

services:
  letsencrypt:
    image: certbot/dns-route53
    command: sh -c "certbot certonly -d kamranvalijonov.com -d *.code.kamranvalijonov.com --dns-route53 -m kamran.valijonov@yoona.ai --agree-tos --non-interactive --server https://acme-v02.api.letsencrypt.org/directory --dns-route53-propagation-seconds 600"
    entrypoint: ""
    volumes:
      - letsencrypt:/etc/letsencrypt
    environment:
      - TERM=xterm
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "80:80"

volumes:
  letsencrypt:
    name: letsencrypt_keys